name: Dependencies

on:
  pull_request_target

jobs:
  approve-dependabot:
    runs-on: ubuntu-latest

    steps:
      - uses: hmarr/auto-approve-action@v2
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}